const ROLES = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
})

const AUDIT_ACTIONS = Object.freeze({
  LOGIN: 'LOGIN',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  LOGOUT_ALL: 'LOGOUT_ALL',
  TOKEN_REFRESH: 'TOKEN_REFRESH',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  PASSWORD_RESET: 'PASSWORD_RESET',
  PROFILE_UPDATE: 'PROFILE_UPDATE',
  ADMIN_CREATE: 'ADMIN_CREATE',
  ADMIN_UPDATE: 'ADMIN_UPDATE',
  ADMIN_DELETE: 'ADMIN_DELETE',
  ADMIN_STATUS_TOGGLE: 'ADMIN_STATUS_TOGGLE',
  SESSION_REVOKED: 'SESSION_REVOKED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
})

const TARGET_TYPES = Object.freeze({
  ADMIN: 'ADMIN',
  SESSION: 'SESSION',
  SYSTEM: 'SYSTEM',
})

const AUDIT_SEVERITY = Object.freeze({
  INFO: 'INFO',
  WARNING: 'WARNING',
  CRITICAL: 'CRITICAL',
})

const ACTION_SEVERITY = Object.freeze({
  LOGIN: AUDIT_SEVERITY.INFO,
  LOGIN_FAILED: AUDIT_SEVERITY.WARNING,
  LOGOUT: AUDIT_SEVERITY.INFO,
  LOGOUT_ALL: AUDIT_SEVERITY.WARNING,
  TOKEN_REFRESH: AUDIT_SEVERITY.INFO,
  PASSWORD_CHANGE: AUDIT_SEVERITY.WARNING,
  PASSWORD_RESET: AUDIT_SEVERITY.WARNING,
  PROFILE_UPDATE: AUDIT_SEVERITY.INFO,
  ADMIN_CREATE: AUDIT_SEVERITY.INFO,
  ADMIN_UPDATE: AUDIT_SEVERITY.INFO,
  ADMIN_DELETE: AUDIT_SEVERITY.CRITICAL,
  ADMIN_STATUS_TOGGLE: AUDIT_SEVERITY.WARNING,
  SESSION_REVOKED: AUDIT_SEVERITY.INFO,
  ACCOUNT_LOCKED: AUDIT_SEVERITY.CRITICAL,
  TOKEN_REUSE_DETECTED: AUDIT_SEVERITY.CRITICAL,
})

const ENTITY_LINKS = Object.freeze({
  ADMIN: (id) => `/admins`,
  SESSION: () => `/profile`,
  SYSTEM: null,
})

module.exports = {
  ROLES,
  AUDIT_ACTIONS,
  TARGET_TYPES,
  AUDIT_SEVERITY,
  ACTION_SEVERITY,
  ENTITY_LINKS,
}
